import json
from typing import Dict, Any, List
from langchain_core.messages import SystemMessage, HumanMessage
from app.graph.state import HavenkeepState
from app.governance.model_adapter import ModelProviderAdapter
from app.governance.policy_engine import PolicyEngine, PolicyVerdict
from app.governance.cost_tracker import CostTracker
from app.governance.audit_logger import AuditLogger

EXECUTOR_SYSTEM_PROMPT = """You are the Havenkeep Governed-Lane Executor Agent.
Your role is to safely execute structured plan steps generated by the Planner Agent.
Ensure all proposed tool actions comply with security policies and produce concise, audit-ready execution summaries."""

class ExecutorNode:
    """
    Executor Node that executes steps in the generated plan.
    Routes every tool call through PolicyEngine to enforce approval gates (Tier 1/2 actions),
    tracks costs, and logs execution transitions.
    """

    @classmethod
    async def run(cls, state: HavenkeepState) -> Dict[str, Any]:
        prompt = state.get("task_prompt", "")
        plan_steps = state.get("plan_steps", [])
        session_id = state.get("session_id", "session-unknown")

        model = ModelProviderAdapter.get_model(role="executor", temperature=0.2)

        # Evaluate tools for planned steps against PolicyEngine
        pending_approval = False
        approval_reason = None
        pending_tool_call = None

        for step in plan_steps:
            tool_name = step.get("tool_name", "internal_compute")
            tool_args = step.get("tool_args", {})
            verdict: PolicyVerdict = PolicyEngine.evaluate_tool_call(
                agent_role="executor",
                tool_name=tool_name,
                tool_args=tool_args
            )

            if verdict.requires_human_interrupt:
                pending_approval = True
                approval_reason = f"Step '{step.get('description', '')}' requires approval: {verdict.reason}"
                pending_tool_call = {"tool_name": tool_name, "tool_args": tool_args, "step_id": step.get("step_id")}
                break

        messages = [
            SystemMessage(content=EXECUTOR_SYSTEM_PROMPT),
            HumanMessage(
                content=f"Original Prompt: {prompt}\n\nPlan Steps:\n{json.dumps(plan_steps, indent=2)}\n\nProvide execution summary."
            )
        ]

        response = await model.ainvoke(messages)
        content = response.content if hasattr(response, "content") else str(response)

        # Token usage & dynamic cost pricing lookup
        usage = getattr(response, "usage_metadata", {}) or {}
        prompt_tokens = usage.get("input_tokens", 300)
        completion_tokens = usage.get("output_tokens", 200)

        model_name = ModelProviderAdapter.get_model_name("executor")
        call_cost = CostTracker.calculate_cost(model_name, prompt_tokens, completion_tokens)
        current_cost = state.get("cumulative_cost_usd", 0.0)
        new_cost, is_soft_warn, is_hard_halt = CostTracker.update_and_check_budget(
            current_cost, call_cost, state.get("soft_budget_usd", 0.50), state.get("hard_budget_usd", 2.00)
        )

        # Audit Log
        await AuditLogger.log_event(
            session_id=session_id,
            agent_name="Executor",
            lane="governed_lane",
            step_name="plan_execution",
            event_type="EXECUTOR_PAUSED_APPROVAL" if pending_approval else "EXECUTOR_EXECUTED",
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            cost_usd=call_cost,
            tool_name=pending_tool_call["tool_name"] if pending_tool_call else "plan_execution",
            policy_verdict="APPROVAL_REQUIRED" if pending_approval else "ALLOWED",
            payload={
                "pending_approval": pending_approval,
                "approval_reason": approval_reason,
                "execution_snippet": content[:120]
            }
        )

        return {
            "final_output": content,
            "approval_required": pending_approval,
            "approval_reason": approval_reason,
            "pending_tool_call": pending_tool_call,
            "cumulative_prompt_tokens": state.get("cumulative_prompt_tokens", 0) + prompt_tokens,
            "cumulative_completion_tokens": state.get("cumulative_completion_tokens", 0) + completion_tokens,
            "cumulative_cost_usd": new_cost,
            "is_budget_exceeded": is_hard_halt
        }
