import json
import re
from typing import Dict, Any
from langchain_core.messages import SystemMessage, HumanMessage
from app.graph.state import HavenkeepState
from app.governance.model_adapter import ModelProviderAdapter
from app.governance.cost_tracker import CostTracker
from app.governance.audit_logger import AuditLogger

GUARDRAIL_SYSTEM_PROMPT = """You are the Havenkeep Fast-Lane Guardrail Node.
Your role is to conduct a fast quality and safety check on the response generated by the Fast-Lane Worker.

CHECKLIST CRITERIA:
1. Safety & Compliance: Ensure the response contains no malicious instructions or unauthorized system calls.
2. Relevance: Verify the answer directly addresses the original user prompt.
3. Clarity: Ensure formatting is clean, coherent, and well-structured.

Respond in structured JSON format:
{
  "passed": true,
  "feedback": "Response is safe, relevant, and well-formatted.",
  "adjusted_output": null
}
If major revisions are required, set passed: false and provide an adjusted_output string.
"""

class FastLaneGuardrailNode:
    """
    Lightweight Guardrail Node that runs a fast rubric-based check before returning worker output to the user.
    """

    @classmethod
    async def run(cls, state: HavenkeepState) -> Dict[str, Any]:
        prompt = state.get("task_prompt", "")
        worker_output = state.get("final_output", "")
        session_id = state.get("session_id", "session-unknown")

        model = ModelProviderAdapter.get_model(role="critic", temperature=0.0)

        messages = [
            SystemMessage(content=GUARDRAIL_SYSTEM_PROMPT),
            HumanMessage(content=f"Original Prompt:\n{prompt}\n\nWorker Output:\n{worker_output}")
        ]

        response = await model.ainvoke(messages)
        content = response.content if hasattr(response, "content") else str(response)

        # Token & Cost Calculation
        usage = getattr(response, "usage_metadata", {}) or {}
        prompt_tokens = usage.get("input_tokens", 120)
        completion_tokens = usage.get("output_tokens", 60)

        model_name = ModelProviderAdapter.get_model_name("critic")
        call_cost = CostTracker.calculate_cost(model_name, prompt_tokens, completion_tokens)
        current_cost = state.get("cumulative_cost_usd", 0.0)
        new_cost, is_soft_warn, is_hard_halt = CostTracker.update_and_check_budget(
            current_cost, call_cost, state.get("soft_budget_usd", 0.50), state.get("hard_budget_usd", 2.00)
        )

        # Parse Guardrail Output
        passed = True
        feedback = "Passed quality and safety guardrail check."
        final_output = worker_output

        try:
            json_match = re.search(r"\{.*\}", content, re.DOTALL)
            raw_json = json_match.group(0) if json_match else content
            data = json.loads(raw_json)
            if isinstance(data, dict):
                passed = data.get("passed", True)
                feedback = data.get("feedback", feedback)
                if data.get("adjusted_output"):
                    final_output = data["adjusted_output"]
        except Exception:
            # If JSON parsing fails, retain original worker output as safe default
            pass

        # Log Guardrail Event
        await AuditLogger.log_event(
            session_id=session_id,
            agent_name="FastLaneGuardrail",
            lane="fast_lane",
            step_name="guardrail_check",
            event_type="GUARDRAIL_PASSED" if passed else "GUARDRAIL_REVISED",
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            cost_usd=call_cost,
            critic_verdict="PASS" if passed else "REVISED",
            payload={
                "feedback": feedback,
                "passed": passed
            }
        )

        return {
            "final_output": final_output,
            "critic_verdict": "PASS" if passed else "REVISED",
            "critic_feedback": feedback,
            "cumulative_prompt_tokens": state.get("cumulative_prompt_tokens", 0) + prompt_tokens,
            "cumulative_completion_tokens": state.get("cumulative_completion_tokens", 0) + completion_tokens,
            "cumulative_cost_usd": new_cost,
            "is_budget_exceeded": is_hard_halt
        }
